# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Unit5Assessment' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Unit5Assessment
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  pod 'Firebase/Storage'
  pod 'Kingfisher'

  target 'Unit5AssessmentTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
